//NOTE: try-catch helyett ebbe wrappeljÃ¼k a controllereket
module.exports = func => (req, res, next) =>
    Promise.resolve(func(req, res, next))
           .catch(next);